<a href="https://colab.research.google.com/github/raketic-ognjen/Market-Watch-Tech-Analysis/blob/main/TechAnalysis_Team6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color = "DeepSkyBlue"><center>**Market Watch - Technical Analysis**</center></font>

## <center>**Core Idea Explanation**</center>

### Adding Packages - Libraries:
1. Pandas(pandas data reader)
2. yfinance
3. NumPy(linAlg)
4. SciPy(optimize and stats)
5. Plotly(graph objects and subplots)
6. Statsmodels.api
7. DateTime

In [1]:
import pandas as pd
import yfinance as yf
import numpy as np
import numpy.linalg as LA
import scipy as sp
import scipy.optimize as sco
import scipy.stats as st
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import statsmodels.api as sm
import pandas_datareader as pdr
import datetime as dt

In [74]:
from google.colab import files
uploaded0=files.upload()

Saving MCF_INV.py to MCF_INV.py


In [75]:
import MCF_INV as inv

### <center>*First step*</center>

> First of all, I want to appologise to my team and to You, professor, because I did not show up on the Market Watch Game due to my **TCL knee injury.** Because of that I will do next things:
1.   **Portfolio Optimization**
2.   **Efficient Frontiers**
3.   **CAPM Model**
4.   **Sharpe's Ratio**
5.   **Testing Portfolio Performances**
6.   **Robustness portfolio**
7.   **Black-Litterman model**
8.   **Comparing with Non-Technical Result of my group**



### <center>*Second Step*</center>

According to my group starting portfolio, we use 6 companies:
1. Starbucks - SBUX - 9 stocks 0.13 weight
2. Coca Cola - KO - 15  stocks 0.22 weight
3. Microsoft - MSFT 3 stocks 0.04 weight
4. Pfizer - PFE 25 stocks 0.37 weight
5. Nike - NKE 8 stocks 0.12 weight
6. Exxon Mobil - XOM 8 stocks 0.12 weight

Later Non Technical portfolio  had 83 trades and a lot buying-selling companies, so for this analysis I will use only this 6 stocks

According to TA starting portfolio, we use 6 companies:
1. Astra Zeneca - AZN - 25 stocks 0.37
2. Nvidia - NVD - 3 stocks 0.04
3. Under Armour - UA - 8 stocks 0.12
4. Rivian - RIVN - 8 stocks 0.12
5. Carnival Corporation - CCL - 9 Stocks 0.13
6. McDonalds - MCD - 15 stocks 0.22

### NTA and TA portfolio

In [2]:
#Non Technical Analysis Portfolio start
ntaportf= ['SBUX', 'KO', 'MSFT','PFE', 'NKE', 'XOM']

#Technical Analysis portfolio start
taportf = ['AZN', 'NVDA', 'UA', 'RIVN', 'CCL', 'MCD']

### Prices for NTA portfolio

In [3]:
#Prices for non Technical Analysis portfolio from 21th April to 18th May
ntaprices= yf.download(ntaportf, start='2023-04-21',end='2023-05-18')['Adj Close']
ntaprices.head()

[*********************100%%**********************]  6 of 6 completed


KO        MSFT         NKE        PFE        SBUX  \
Date                                                                   
2023-04-21  63.565891  284.534271  124.699898  39.341244  107.082939   
2023-04-24  63.466644  280.561340  126.249573  39.047722  108.171684   
2023-04-25  63.367397  274.238617  123.835655  38.480259  108.221169   
2023-04-26  63.069668  294.103027  123.021072  37.795383  110.329376   
2023-04-27  63.198685  303.522461  124.868767  37.903004  111.596283   

                   XOM  
Date                    
2023-04-21  114.076866  
2023-04-24  116.230362  
2023-04-25  114.578362  
2023-04-26  113.526184  
2023-04-27  114.883194

### Prices for TA portfolio

In [4]:
#Prices for Technical Analysis portfolio form 21th April to 18th May
taprices = yf.download(taportf,start='2023-04-21', end='2023-05-18')['Adj Close']
taprices.head()

[*********************100%%**********************]  6 of 6 completed


AZN   CCL         MCD        NVDA   RIVN    UA
Date                                                            
2023-04-21  75.106819  9.38  288.964294  271.139618  12.25  8.02
2023-04-24  75.315445  9.28  290.092255  270.369751  12.36  8.09
2023-04-25  75.166435  8.96  288.420135  262.361237  12.00  7.80
2023-04-26  73.169540  8.76  286.688690  269.509888  12.04  7.87
2023-04-27  73.298691  8.90  291.596130  272.209412  12.67  7.95

### Returns and .prod() method for NTA portfolio

In [5]:
#Returns of ntaportf
rets1 = ntaprices.pct_change().dropna()
rets1.head()

KO      MSFT       NKE       PFE      SBUX       XOM
Date                                                                  
2023-04-24 -0.001561 -0.013963  0.012427 -0.007461  0.010167  0.018878
2023-04-25 -0.001564 -0.022536 -0.019120 -0.014533  0.000457 -0.014213
2023-04-26 -0.004698  0.072435 -0.006578 -0.017798  0.019481 -0.009183
2023-04-27  0.002046  0.032028  0.015019  0.002847  0.011483  0.011953
2023-04-28  0.007381  0.007972  0.008115  0.003872  0.013658  0.012925

I am doing .prod() method to see cumulative prod for period from 21st April to the 18th May.

In [6]:
(rets1+1).prod()

KO      0.985948
MSFT    1.101226
NKE     0.931889
PFE     0.923841
SBUX    0.981757
XOM     0.911383
dtype: float64

We can see here that only Microsoft has positive cumulative return(10.12%). The Biggest underperformer is Exxon Mobil (-8.87%)

### Returns and .prod() method for TA portfolio

In [7]:
#returns of taportf
rets2 = taprices.pct_change().dropna()
rets2.head()

AZN       CCL       MCD      NVDA      RIVN        UA
Date                                                                  
2023-04-24  0.002778 -0.010661  0.003903 -0.002839  0.008980  0.008728
2023-04-25 -0.001978 -0.034483 -0.005764 -0.029621 -0.029126 -0.035847
2023-04-26 -0.026566 -0.022321 -0.006003  0.027247  0.003333  0.008974
2023-04-27  0.001765  0.015982  0.017118  0.010016  0.052326  0.010165
2023-04-28 -0.007590  0.034832  0.003495  0.019209  0.011839  0.011321

I repeat doing .prod() method to see cumulative prod for period from 21st April to the 18th May for ta portfolio.

In [8]:
(rets2+1).prod()

AZN     0.988095
CCL     1.176972
MCD     1.004794
NVDA    1.112799
RIVN    1.094694
UA      0.857855
dtype: float64

We Can see that we have 4 cumulative returns in plus. Winner is Carnival Corporation (CCL) with 17.70% and the biggest losser is Under Armour(UA) with -14.31%

### Expected Returns with .mean() method for NTA portfolio

I will do now expected return with .mean() for non ta portfolio. I will do it on the Daily basis and for the entire period(20 working days)

In [9]:
#Daily expected returns
exp_ret1 = rets1.mean()
print(rets1.mean())
print("*"*50)
#Entire Period daily returns(20 days)
print(exp_ret1*20)

KO     -0.000774
MSFT    0.005571
NKE    -0.003816
PFE    -0.004365
SBUX   -0.000726
XOM    -0.004975
dtype: float64
**************************************************
KO     -0.015488
MSFT    0.111419
NKE    -0.076319
PFE    -0.087303
SBUX   -0.014521
XOM    -0.099498
dtype: float64


As we can see, expected return for each of this stock in first portfolio is mostly negative.

### Expected Returns with .mean() method for TA portfolio

Now I will do now expected return with .mean() for non ta portfolio. I will do it on the Daily basis and for the entire period(20 working days)

In [10]:
#Daily Expected Returns
exp_ret2= rets2.mean()
print(rets2.mean())
print("*"*50)
#Expected Return for the entire period(20 days)
print(exp_ret2*20)

AZN    -0.000632
CCL     0.009630
MCD     0.000283
NVDA    0.006184
RIVN    0.005442
UA     -0.008147
dtype: float64
**************************************************
AZN    -0.012631
CCL     0.192596
MCD     0.005670
NVDA    0.123679
RIVN    0.108833
UA     -0.162944
dtype: float64


We can see that this portfolio is mostly positive

### Volatility for NTA portfolio

Now we are doing Volatility for NTA portfolio

In [11]:
#basic
vol1=rets1.std()*20**0.5
print(vol1)
print("*"*50)

#Numpy method
np.std(rets1,ddof=1)*np.sqrt(20)

KO      0.022026
MSFT    0.093343
NKE     0.063459
PFE     0.033127
SBUX    0.109212
XOM     0.083848
dtype: float64
**************************************************


KO      0.022026
MSFT    0.093343
NKE     0.063459
PFE     0.033127
SBUX    0.109212
XOM     0.083848
dtype: float64

### Volatility for TA portfolio

And now Volatility for TA portfolio

In [12]:
#Basic
vol2=rets2.std()*20**0.5
print(vol2)
print("*"*50)

#Numpy method
np.std(rets2,ddof=1)*np.sqrt(20)

AZN     0.037562
CCL     0.152024
MCD     0.027501
NVDA    0.098716
RIVN    0.130052
UA      0.118295
dtype: float64
**************************************************


AZN     0.037562
CCL     0.152024
MCD     0.027501
NVDA    0.098716
RIVN    0.130052
UA      0.118295
dtype: float64

### Risk-adjusted performance ratios for NTA portfolio

In [13]:
#Comparison using the sample mean
exp_ret1/vol1

KO     -0.035159
MSFT    0.059683
NKE    -0.060133
PFE    -0.131770
SBUX   -0.006648
XOM    -0.059332
dtype: float64

### Risk-adjusted performance ratios for TA portfolio

In [14]:
exp_ret2/vol2

AZN    -0.016813
CCL     0.063344
MCD     0.010309
NVDA    0.062644
RIVN    0.041842
UA     -0.068872
dtype: float64

### Sharpe for NTA portfolio

In [15]:
rf=0.03
sharpe1=(exp_ret1-rf)/vol1
sharpe1

KO     -1.397200
MSFT   -0.261714
NKE    -0.532882
PFE    -1.037377
SBUX   -0.281342
XOM    -0.417121
dtype: float64

### Sharpe for TA portfolio

In [16]:
rf=0.03
sharpe2=(exp_ret2-rf)/vol2
sharpe2

AZN    -0.815485
CCL    -0.133994
MCD    -1.080551
NVDA   -0.241259
RIVN   -0.188835
UA     -0.322475
dtype: float64

### Expected Return function for NTA portfolio

In [93]:
#Arithmetic mean
er1=inv.expRet(rets1,20)
print(er1)
print("*"*50)
#Geometric Mean
print(inv.expRet(rets1,20,True))

KO     -0.015488
MSFT    0.111419
NKE    -0.076319
PFE    -0.087303
SBUX   -0.014521
XOM    -0.099498
dtype: float64
**************************************************
KO     -0.015601
MSFT    0.113088
NKE    -0.075387
PFE    -0.084254
SBUX   -0.020250
XOM    -0.097965
dtype: float64


### Expected Return function for TA portfolio

In [92]:
#Arithmetic Mean
er2=inv.expRet(rets2,20)
print(er2)
print("*"*50)
#Geometric Mean
print(inv.expRet(rets2,20,True))

AZN    -0.012631
CCL     0.192596
MCD     0.005670
NVDA    0.123679
RIVN    0.108833
UA     -0.162944
dtype: float64
**************************************************
AZN    -0.013219
CCL     0.198475
MCD     0.005328
NVDA    0.126093
RIVN    0.105754
UA     -0.156635
dtype: float64


### Covariance and calculating portfolio variance for NTA portfolio

In [116]:
w1= [0.13,0.22,0.04,0.37,0.12,0.12]

In [107]:
#covariance matrix
CovM1 = rets1.cov()*20
CovM1

KO      MSFT       NKE       PFE      SBUX       XOM
KO    0.000485 -0.000067  0.000609  0.000310  0.000933  0.000602
MSFT -0.000067  0.008713  0.000943 -0.000354  0.003042  0.001079
NKE   0.000609  0.000943  0.004027  0.001131  0.001645  0.003108
PFE   0.000310 -0.000354  0.001131  0.001097  0.001430  0.000651
SBUX  0.000933  0.003042  0.001645  0.001430  0.011927  0.003528
XOM   0.000602  0.001079  0.003108  0.000651  0.003528  0.007031

In [110]:
 # Variances of individual stocks
var1 = np.diag(CovM1)
var1

array([0.00048513, 0.00871287, 0.004027  , 0.0010974 , 0.01192734,
       0.00703053])

In [111]:
# Standard deviations of volatilities of individual stocks
np.sqrt(var1)

array([0.02202576, 0.09334274, 0.06345867, 0.03312696, 0.10921234,
       0.08384826])

In [136]:
# Calculating portfolio variance
portfvar1=w1@CovM1@w1
portfvar1

0.0014818727572691371

In [121]:
#Portfolio volatility is equal to the square root of portfolio variance
np.sqrt(portfvar1)

0.03849510043199182

In [122]:
#Correlations
rets1.corr()

KO      MSFT       NKE       PFE      SBUX       XOM
KO    1.000000 -0.032358  0.435387  0.424547  0.387916  0.326234
MSFT -0.032358  1.000000  0.159228 -0.114468  0.298424  0.137834
NKE   0.435387  0.159228  1.000000  0.537926  0.237364  0.584053
PFE   0.424547 -0.114468  0.537926  1.000000  0.395295  0.234397
SBUX  0.387916  0.298424  0.237364  0.395295  1.000000  0.385224
XOM   0.326234  0.137834  0.584053  0.234397  0.385224  1.000000

In [126]:
# Variance and standard deviation of NTA portfolio portfolio
inv.pV(w1,rets1),inv.pV(w1,rets1,vol=True)

(0.018671596741591127, 0.1366440512484577)

### Covariance and calculating portfolio variance for NTA portfolio

In [128]:
w2 = ([1/6]*6)

In [131]:
#covariance matrix
CovM2 = rets2.cov()*20
CovM2

AZN       CCL       MCD      NVDA      RIVN        UA
AZN   0.001411  0.001401  0.000194 -0.000445  0.000461  0.000393
CCL   0.001401  0.023111  0.001084  0.010493  0.013486  0.008330
MCD   0.000194  0.001084  0.000756  0.000754  0.001136  0.000539
NVDA -0.000445  0.010493  0.000754  0.009745  0.005505  0.005472
RIVN  0.000461  0.013486  0.001136  0.005505  0.016913  0.007047
UA    0.000393  0.008330  0.000539  0.005472  0.007047  0.013994

In [132]:
 # Variances of individual stocks
var2 = np.diag(CovM2)
var2

array([0.00141093, 0.0231112 , 0.00075632, 0.00974484, 0.01691347,
       0.01399374])

In [133]:
# Standard deviations of volatilities of individual stocks
np.sqrt(var2)

array([0.03756236, 0.15202369, 0.02750124, 0.09871593, 0.13005178,
       0.11829513])

In [134]:
# Calculating portfolio variance
portfvar2=w2@CovM2@w2
portfvar2

0.0049342709865557765

In [137]:
#Correlations
rets2.corr()

AZN       CCL       MCD      NVDA      RIVN        UA
AZN   1.000000  0.245359  0.188253 -0.119970  0.094434  0.088344
CCL   0.245359  1.000000  0.259313  0.699216  0.682132  0.463172
MCD   0.188253  0.259313  1.000000  0.277888  0.317498  0.165609
NVDA -0.119970  0.699216  0.277888  1.000000  0.428836  0.468629
RIVN  0.094434  0.682132  0.317498  0.428836  1.000000  0.458061
UA    0.088344  0.463172  0.165609  0.468629  0.458061  1.000000

In [138]:
# Variance and standard deviation of TA portfolio portfolio
inv.pV(w2,rets2),inv.pV(w2,rets2,vol=True)

(0.06217181443060278, 0.2493427649453715)

### MVP of NTA Portfolio

In [142]:
result1= sco.minimize(lambda w1: inv.pV(w1,rets1),[0.13,0.22,0.04,0.37,0.12,0.12],
                      constraints = dict(type='eq', fun=lambda w1: sum(w1)-1))
result1.x

array([ 0.74030323,  0.09975316, -0.16081054,  0.36386157, -0.09312031,
        0.0500129 ])