<a href="https://colab.research.google.com/github/raketic-ognjen/Market-Watch-Tech-Analysis/blob/main/TechAnalysis_Team6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color = "DeepSkyBlue"><center>**Market Watch - Technical Analysis**</center></font>

## <center>**Core Idea Explanation**</center>

### Adding Packages - Libraries:
1. Pandas(pandas data reader)
2. yfinance
3. NumPy(linAlg)
4. SciPy(optimize and stats)
5. Plotly(graph objects and subplots)
6. Statsmodels.api
7. DateTime

In [1]:
import pandas as pd
import yfinance as yf
import numpy as np
import numpy.linalg as LA
import scipy as sp
import scipy.optimize as sco
import scipy.stats as st
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import statsmodels.api as sm
import pandas_datareader as pdr
import datetime as dt

In [2]:
from google.colab import files
uploaded0=files.upload()

Saving MCF_INV.py to MCF_INV.py


In [3]:
import MCF_INV as inv

### <center>*First step*</center>

> First of all, I want to appologise to my team and to You, professor, because I did not show up on the Market Watch Game due to my **TCL knee injury.** Because of that I will do next things:
1.   **Portfolio Optimization**
2.   **Efficient Frontiers**
3.   **CAPM Model**
4.   **Sharpe's Ratio**
5.   **Testing Portfolio Performances**
6.   **Robustness portfolio**
7.   **Black-Litterman model**
8.   **Comparing with Non-Technical Result of my group**



### <center>*Second Step*</center>

According to my group starting portfolio, we use 6 companies:
1. Starbucks - SBUX - 9 stocks 0.13 weight
2. Coca Cola - KO - 15  stocks 0.22 weight
3. Microsoft - MSFT 3 stocks 0.04 weight
4. Pfizer - PFE 25 stocks 0.37 weight
5. Nike - NKE 8 stocks 0.12 weight
6. Exxon Mobil - XOM 8 stocks 0.12 weight

Later Non Technical portfolio  had 83 trades and a lot buying-selling companies, so for this analysis I will use only this 6 stocks

According to TA starting portfolio, we use 6 companies:
1. Astra Zeneca - AZN -  
2. Nvidia - NVD -
3. Novartis - NVS
4. Rivian - RIVN
5. Carnival Corporation - CCL
6. Norwegian Cruise Company -NCLH

### NTA and TA portfolio

In [40]:
#Non Technical Analysis Portfolio start
ntaportf= ['SBUX', 'KO', 'MSFT','PFE', 'NKE', 'XOM']

#Technical Analysis portfolio start
taportf = ['AZN', 'NVDA', 'NVS', 'RIVN', 'CCL', 'NCLH']

### Prices for NTA portfolio

In [41]:
#Prices for non Technical Analysis portfolio from 18th May 2022 to 18th May 2023
ntaprices= yf.download(ntaportf, start='2022-05-18',end='2023-05-18')['Adj Close']
ntaprices.head()

[*********************100%%**********************]  6 of 6 completed


KO        MSFT         NKE        PFE       SBUX        XOM
Date                                                                          
2022-05-18  58.991207  251.115845  107.430824  48.074242  69.402298  86.907913
2022-05-19  57.834518  250.186813  104.552773  48.312706  70.035172  87.377693
2022-05-20  58.779152  249.613586  106.085114  50.048721  71.456703  88.067970
2022-05-23  60.591297  257.609192  106.703934  50.439793  71.485924  90.014175
2022-05-24  61.709427  256.591217  105.387695  50.945343  70.804375  90.503120

### Prices for TA portfolio

In [43]:
#Prices for Technical Analysis portfolio form 18th May 2022 to 18th May 2023
taprices = yf.download(taportf,start='2022-05-18', end='2023-05-18')['Adj Close']
taprices.head()

[*********************100%%**********************]  6 of 6 completed


AZN    CCL   NCLH        NVDA        NVS       RIVN
Date                                                                 
2022-05-18  61.572063  13.84  15.90  169.190399  84.028160  27.290001
2022-05-19  62.758389  13.58  15.95  171.048355  84.957764  29.610001
2022-05-20  64.382278  13.13  15.30  166.753143  85.695686  28.920000
2022-05-23  64.576775  13.11  15.10  168.790863  86.931961  27.990000
2022-05-24  64.810143  11.76  13.29  161.359177  88.101151  26.530001

### Returns and .prod() method for NTA portfolio

In [44]:
#Returns of ntaportf
rets1 = ntaprices.pct_change().dropna()
rets1.head()

KO      MSFT       NKE       PFE      SBUX       XOM
Date                                                                  
2022-05-19 -0.019608 -0.003700 -0.026790  0.004960  0.009119  0.005405
2022-05-20  0.016333 -0.002291  0.014656  0.035933  0.020297  0.007900
2022-05-23  0.030830  0.032032  0.005833  0.007814  0.000409  0.022099
2022-05-24  0.018454 -0.003952 -0.012335  0.010023 -0.009534  0.005432
2022-05-25  0.000781  0.011170  0.008482  0.005617 -0.003300  0.020127

I am doing .prod() method to see cumulative prod for period from 21st April to the 18th May.

In [47]:
(rets1+1).prod()

KO      1.062407
MSFT    1.247777
NKE     1.081686
PFE     0.756020
SBUX    1.514783
XOM     1.196298
dtype: float64

We can see here that only Microsoft has positive cumulative return(10.12%). The Biggest underperformer is Exxon Mobil (-8.87%)

### Returns and .prod() method for TA portfolio

In [45]:
#returns of taportf
rets2 = taprices.pct_change().dropna()
rets2.head()

AZN       CCL      NCLH      NVDA       NVS      RIVN
Date                                                                  
2022-05-19  0.019267 -0.018786  0.003145  0.010981  0.011063  0.085013
2022-05-20  0.025875 -0.033137 -0.040752 -0.025111  0.008686 -0.023303
2022-05-23  0.003021 -0.001523 -0.013072  0.012220  0.014426 -0.032158
2022-05-24  0.003614 -0.102975 -0.119868 -0.044029  0.013449 -0.052161
2022-05-25  0.002401  0.035714  0.033108  0.050823 -0.007397  0.027139

I repeat doing .prod() method to see cumulative prod for period from 21st April to the 18th May for ta portfolio.

In [48]:
(rets2+1).prod()

AZN     1.205298
CCL     0.797688
NCLH    0.902516
NVDA    1.783340
NVS     1.204596
RIVN    0.491389
dtype: float64

We Can see that we have 4 cumulative returns in plus. Winner is Carnival Corporation (CCL) with 17.70% and the biggest losser is Under Armour(UA) with -14.31%

### Expected Returns with .mean() method for NTA portfolio

I will do now expected return with .mean() for non ta portfolio. I will do it on the Daily basis and for the entire period(20 working days)

In [52]:
#Daily expected returns
exp_ret1 = rets1.mean()
print(rets1.mean())
print("*"*50)
#Entire Period daily returns(252 days)
print(exp_ret1*252)

KO      0.000296
MSFT    0.001101
NKE     0.000597
PFE    -0.001012
SBUX    0.001834
XOM     0.000927
dtype: float64
**************************************************
KO      0.074560
MSFT    0.277487
NKE     0.150414
PFE    -0.255115
SBUX    0.462203
XOM     0.233655
dtype: float64


As we can see, expected return for each of this stock in first portfolio is mostly negative.

### Expected Returns with .mean() method for TA portfolio

Now I will do now expected return with .mean() for non ta portfolio. I will do it on the Daily basis and for the entire period(20 working days)

In [51]:
#Daily Expected Returns
exp_ret2= rets2.mean()
print(rets2.mean())
print("*"*50)
#Expected Return for the entire period(20 days)
print(exp_ret2*252)

AZN     0.000857
CCL     0.000200
NCLH    0.000585
NVDA    0.002927
NVS     0.000821
RIVN   -0.001771
dtype: float64
**************************************************
AZN     0.216026
CCL     0.050373
NCLH    0.147429
NVDA    0.737566
NVS     0.206911
RIVN   -0.446227
dtype: float64


We can see that this portfolio is mostly positive

### Volatility for NTA portfolio

Now we are doing Volatility for NTA portfolio

In [53]:
#basic
vol1=rets1.std()*252**0.5
print(vol1)
print("*"*50)

#Numpy method
np.std(rets1,ddof=1)*np.sqrt(252)

KO      0.164875
MSFT    0.330762
NKE     0.377908
PFE     0.231302
SBUX    0.294473
XOM     0.326060
dtype: float64
**************************************************


KO      0.164875
MSFT    0.330762
NKE     0.377908
PFE     0.231302
SBUX    0.294473
XOM     0.326060
dtype: float64

### Volatility for TA portfolio

And now Volatility for TA portfolio

In [54]:
#Basic
vol2=rets2.std()*252**0.5
print(vol2)
print("*"*50)

#Numpy method
np.std(rets2,ddof=1)*np.sqrt(252)

AZN     0.236267
CCL     0.740221
NCLH    0.708718
NVDA    0.557601
NVS     0.197286
RIVN    0.734676
dtype: float64
**************************************************


AZN     0.236267
CCL     0.740221
NCLH    0.708718
NVDA    0.557601
NVS     0.197286
RIVN    0.734676
dtype: float64

### Risk-adjusted performance ratios for NTA portfolio

In [55]:
#Comparison using the sample mean
exp_ret1/vol1

KO      0.001795
MSFT    0.003329
NKE     0.001579
PFE    -0.004377
SBUX    0.006229
XOM     0.002844
dtype: float64

### Risk-adjusted performance ratios for TA portfolio

In [56]:
exp_ret2/vol2

AZN     0.003628
CCL     0.000270
NCLH    0.000825
NVDA    0.005249
NVS     0.004162
RIVN   -0.002410
dtype: float64

### Sharpe for NTA portfolio

In [57]:
rf=0.03
sharpe1=(exp_ret1-rf)/vol1
sharpe1

KO     -0.180161
MSFT   -0.087370
NKE    -0.077805
PFE    -0.134077
SBUX   -0.095648
XOM    -0.089164
dtype: float64

### Sharpe for TA portfolio

In [58]:
rf=0.03
sharpe2=(exp_ret2-rf)/vol2
sharpe2

AZN    -0.123347
CCL    -0.040258
NCLH   -0.041504
NVDA   -0.048553
NVS    -0.147902
RIVN   -0.043245
dtype: float64

### Expected Return function for NTA portfolio

In [62]:
#Arithmetic mean
er1=inv.expRet(rets1,252)
print(er1)
print("*"*50)
#Geometric Mean
print(inv.expRet(rets1,252,True))

KO      0.074560
MSFT    0.277487
NKE     0.150414
PFE    -0.255115
SBUX    0.462203
XOM     0.233655
dtype: float64
**************************************************
KO      0.062922
MSFT    0.249989
NKE     0.082366
PFE    -0.245670
SBUX    0.519823
XOM     0.198014
dtype: float64


### Expected Return function for TA portfolio

In [61]:
#Arithmetic Mean
er2=inv.expRet(rets2,252)
print(er2)
print("*"*50)
#Geometric Mean
print(inv.expRet(rets2,252,True))

AZN     0.216026
CCL     0.050373
NCLH    0.147429
NVDA    0.737566
NVS     0.206911
RIVN   -0.446227
dtype: float64
**************************************************
AZN     0.207100
CCL    -0.203753
NCLH   -0.098224
NVDA    0.791612
NVS     0.206391
RIVN   -0.511396
dtype: float64


### Covariance and calculating portfolio variance for NTA portfolio

In [63]:
w1= [0.13,0.22,0.04,0.37,0.12,0.12]

In [75]:
#covariance matrix
CovM1 = rets1.cov()*252
CovM1

KO      MSFT       NKE       PFE      SBUX       XOM
KO    0.027184  0.025897  0.028215  0.019387  0.021335  0.013322
MSFT  0.025897  0.109404  0.071760  0.029644  0.049979  0.028926
NKE   0.028215  0.071760  0.142815  0.033088  0.068950  0.040897
PFE   0.019387  0.029644  0.033088  0.053501  0.026100  0.018291
SBUX  0.021335  0.049979  0.068950  0.026100  0.086714  0.027693
XOM   0.013322  0.028926  0.040897  0.018291  0.027693  0.106315

In [76]:
 # Variances of individual stocks
var1 = np.diag(CovM1)
var1

array([0.02718378, 0.10940372, 0.1428147 , 0.05350061, 0.08671412,
       0.10631496])

In [77]:
# Standard deviations of volatilities of individual stocks
np.sqrt(var1)

array([0.16487505, 0.33076234, 0.37790832, 0.23130198, 0.29447262,
       0.32605976])

In [78]:
# Calculating portfolio variance
portfvar1=w1@CovM1@w1
portfvar1

0.0378365904275987

In [79]:
#Portfolio volatility is equal to the square root of portfolio variance
np.sqrt(portfvar1)

0.1945162986168478

In [80]:
#Correlations
rets1.corr()

KO      MSFT       NKE       PFE      SBUX       XOM
KO    1.000000  0.474869  0.452838  0.508374  0.439433  0.247813
MSFT  0.474869  1.000000  0.574092  0.387471  0.513130  0.268215
NKE   0.452838  0.574092  1.000000  0.378529  0.619591  0.331903
PFE   0.508374  0.387471  0.378529  1.000000  0.383188  0.242528
SBUX  0.439433  0.513130  0.619591  0.383188  1.000000  0.288417
XOM   0.247813  0.268215  0.331903  0.242528  0.288417  1.000000

In [81]:
# Variance and standard deviation of NTA portfolio portfolio
inv.pV(w1,rets1),inv.pV(w1,rets1,vol=True)

(0.0378365904275987, 0.1945162986168478)

### Covariance and calculating portfolio variance for NTA portfolio

In [82]:
w2 = ([1/6]*6)

In [83]:
#covariance matrix
CovM2 = rets2.cov()*252
CovM2

AZN       CCL      NCLH      NVDA       NVS      RIVN
AZN   0.055822  0.043168  0.034971  0.037852  0.028403  0.025721
CCL   0.043168  0.547928  0.471139  0.236249  0.021131  0.265595
NCLH  0.034971  0.471139  0.502281  0.221196  0.017460  0.236142
NVDA  0.037852  0.236249  0.221196  0.310919  0.018566  0.229809
NVS   0.028403  0.021131  0.017460  0.018566  0.038922  0.013758
RIVN  0.025721  0.265595  0.236142  0.229809  0.013758  0.539750

In [84]:
 # Variances of individual stocks
var2 = np.diag(CovM2)
var2

array([0.05582204, 0.54792757, 0.50228065, 0.3109193 , 0.0389216 ,
       0.53974956])

In [85]:
# Standard deviations of volatilities of individual stocks
np.sqrt(var2)

array([0.23626688, 0.7402213 , 0.70871761, 0.55760138, 0.19728557,
       0.7346765 ])

In [86]:
# Calculating portfolio variance
portfvar2=w2@CovM2@w2
portfvar2

0.16105383812671836

In [87]:
#Portfolio volatility is equal to the square root of portfolio variance
np.sqrt(portfvar2)

0.4013151356810734

In [88]:
#Correlations
rets2.corr()

AZN       CCL      NCLH      NVDA       NVS      RIVN
AZN   1.000000  0.246829  0.208850  0.287320  0.609344  0.148180
CCL   0.246829  1.000000  0.898079  0.572380  0.144698  0.488384
NCLH  0.208850  0.898079  1.000000  0.559731  0.124873  0.453527
NVDA  0.287320  0.572380  0.559731  1.000000  0.168769  0.560979
NVS   0.609344  0.144698  0.124873  0.168769  1.000000  0.094923
RIVN  0.148180  0.488384  0.453527  0.560979  0.094923  1.000000

In [89]:
# Variance and standard deviation of TA portfolio portfolio
inv.pV(w2,rets2),inv.pV(w2,rets2,vol=True)

(0.16105383812671836, 0.4013151356810734)

### MVP of NTA Portfolio

In [90]:
#Optimization of NTA MVP portfolio
result1= sco.minimize(lambda w1: inv.pV(w1,rets1,20),[0.13,0.22,0.04,0.37,0.12,0.12],
                      constraints = dict(type='eq', fun=lambda w1: sum(w1)-1))
print(result1)
print("*"*50)
np.sqrt(result1.fun)

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.0019492578037158402
       x: [ 6.708e-01 -4.546e-02 -8.756e-02  2.651e-01  1.255e-01
            7.160e-02]
     nit: 10
     jac: [ 3.708e-03  3.543e-03  3.732e-03  4.370e-03  4.093e-03
            3.171e-03]
    nfev: 70
    njev: 10
**************************************************


0.04415039981377111

In [96]:
# Expected return on MVP portfolio
per1=inv.per(result1.x,rets1)
print(per1)
print("*"*50)
inv.mvp(rets1,252,True)

0.031352116059618795
**************************************************


{'w': array([ 0.74267209, -0.01525021, -0.0816286 ,  0.15618359,  0.07963707,
         0.11838606]),
 'er': 0.06266430361286296,
 'vol': 0.15427508318686844}

Expected Return on MVP is 3.13%

In [99]:
w1_opt_mvp = inv.mvp(cov_assumed=CovM1)
w1_opt_mvp

array([ 0.74267209, -0.01525021, -0.0816286 ,  0.15618359,  0.07963707,
        0.11838606])

In [100]:
np.sqrt(w1_opt_mvp@CovM1@w1_opt_mvp)

0.15427508318686844

In [101]:
er1@w1_opt_mvp

0.0634888659049114

### MVP of TA portfolio

In [93]:
result2= sco.minimize(lambda w2: inv.pV(w2,rets2,20),[1/6]*6,
                      constraints=[dict(type='eq',fun=lambda w2: sum(w2)-1)])
print(result2)
print("*"*50)
np.sqrt(result2.fun)

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.0027830256558655612
       x: [ 2.765e-01 -8.469e-02  8.635e-02  2.148e-02  6.707e-01
            2.958e-02]
     nit: 20
     jac: [ 5.623e-03  5.289e-03  5.808e-03  5.633e-03  5.474e-03
            5.578e-03]
    nfev: 140
    njev: 20
**************************************************


0.0527543899203238

In [97]:
#Expected return on MVP portfolio
per2=inv.per(result2.x,rets2)
print(per2)
print("*"*50)
inv.mvp(rets2,252,True)

0.20962519390603368
**************************************************


{'w': array([ 0.24927024, -0.05206723,  0.05465122,  0.02012777,  0.69999715,
         0.02802085]),
 'er': 0.20294158925208353,
 'vol': 0.186908395803765}

Expected Return on MVP is 20.96%

In [103]:
w2_opt_mvp = inv.mvp(cov_assumed=CovM2)
w2_opt_mvp

array([ 0.24927024, -0.05206723,  0.05465122,  0.02012777,  0.69999715,
        0.02802085])

In [104]:
np.sqrt(w2_opt_mvp@CovM2@w2_opt_mvp)

0.186908395803765

In [105]:
er2@w2_opt_mvp

0.20646221103583326

### Mean-variance optimization NTA Portfolio

In [107]:
res1 = sco.minimize(lambda w1 : inv.pV(w1,rets1),[0.13,0.22,0.04,0.37,0.12,0.12],
                    constraints=[dict(type='eq',fun=lambda w1:sum(w1)-1),
                                 dict(type='eq',fun=lambda w1:inv.per(w1,rets1)-0.10)])
res1

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.023984841742202848
       x: [ 7.498e-01 -7.639e-03 -9.081e-02  1.004e-01  1.202e-01
            1.281e-01]
     nit: 14
     jac: [ 4.768e-02  4.951e-02  4.897e-02  4.431e-02  5.189e-02
            4.967e-02]
    nfev: 98
    njev: 14

In [109]:
np.sqrt(res1.fun)

0.15487040305430488

So Risk is 15.48%

### Mean-variance optimization for TA Portfolio

In [111]:
res2 = sco.minimize(lambda w2: inv.pV(w2,rets2),[1/6]*6,
                    constraints=[dict(type='eq',fun=lambda w2:sum(w2)-1),
                                 dict(type='eq',fun=lambda w2:inv.per(w2,rets2)-0.10)])
res2

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.037647790100572835
       x: [ 2.732e-01 -2.767e-02  4.999e-02 -9.132e-02  7.004e-01
            9.538e-02]
     nit: 14
     jac: [ 6.939e-02  7.749e-02  7.236e-02  4.279e-02  6.985e-02
            1.032e-01]
    nfev: 98
    njev: 14

In [112]:
np.sqrt(res2.fun)

0.19403038447772256

Risk is 19.40%

In [118]:
target1 = inv.targetP(rets2,0.15,cov_assumed=CovM2,er_assumed=er2)
target1

{'w': array([ 0.26170461, -0.03910555,  0.05201852, -0.0388654 ,  0.70040282,
         0.063845  ]),
 'er': 0.15,
 'vol': 0.1889370478358271}